spring:
  datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:

        format_sql: true
        show_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
